# Generated by Django 4.2.7 on 2023-11-24 05:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('preloved_auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('storeID', models.AutoField(primary_key=True, serialize=False)),
                ('storeName', models.CharField(max_length=255)),
                ('locationID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stores', to='preloved_auth.location')),
                ('shopOwnerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stores', to='preloved_auth.shopowner')),
            ],
        ),
    ]
