# Generated by Django 4.2.7 on 2023-12-06 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_slug_isdeleted_slug_isthumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slug',
            name='slug',
            field=models.CharField(max_length=1048, unique=True),
        ),
    ]
