# Generated by Django 4.2.8 on 2023-12-08 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('preloved_auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('itemID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('isFeminine', models.BooleanField(default=True)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('isTaken', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('tagID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('storeID', models.AutoField(primary_key=True, serialize=False)),
                ('storeName', models.CharField(max_length=255)),
                ('locationID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stores', to='preloved_auth.location')),
                ('shopOwnerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stores', to='preloved_auth.shopowner')),
            ],
        ),
        migrations.CreateModel(
            name='Slug',
            fields=[
                ('slugID', models.AutoField(primary_key=True, serialize=False)),
                ('slug', models.CharField(max_length=1048, unique=True)),
                ('isDeleted', models.IntegerField(default=0)),
                ('isThumbnail', models.IntegerField(default=0)),
                ('itemID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slugs', to='store.item')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='storeID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='store.store'),
        ),
        migrations.CreateModel(
            name='ItemTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.item')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.tag')),
            ],
            options={
                'unique_together': {('item', 'tag')},
            },
        ),
    ]
