# Generated by Django 4.2.8 on 2023-12-08 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slug',
            name='slug',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
