# Generated by Django 4.2.7 on 2023-12-04 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_item_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='slug',
            name='isDeleted',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='slug',
            name='isThumbnail',
            field=models.IntegerField(default=0),
        ),
    ]
