# Generated by Django 4.2.8 on 2024-01-01 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='size',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.size'),
        ),
    ]
