# Generated by Django 4.2.7 on 2023-12-07 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_item_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='isTaken',
            field=models.IntegerField(default=0),
        ),
    ]
