# Generated by Django 4.2.7 on 2023-12-01 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preloved_auth', '0005_alter_shopowner_unique_together_shopowner_isverified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopverification',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
