# Generated by Django 4.2.7 on 2023-12-05 20:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('preloved_auth', '0008_alter_shopverification_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='uID',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
