# Generated by Django 4.2.8 on 2023-12-08 10:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=8, null=True)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=8, null=True)),
                ('name', models.CharField(max_length=256, null=True)),
                ('address_plain', models.CharField(max_length=1086)),
            ],
        ),
        migrations.CreateModel(
            name='ShopOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phoneNumber', models.CharField(max_length=20)),
                ('isVerified', models.IntegerField(default=0)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('locationID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='preloved_auth.location')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('address', models.CharField(max_length=256)),
                ('locationID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='preloved_auth.location')),
                ('ownerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='preloved_auth.shopowner')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ShopVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idSlug1', models.CharField(max_length=256)),
                ('idSlug2', models.CharField(max_length=256)),
                ('selfieSlug', models.CharField(max_length=256)),
                ('status', models.IntegerField(default=0)),
                ('shopOwnerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='preloved_auth.shopowner')),
            ],
        ),
        migrations.CreateModel(
            name='ShopUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_no', models.CharField(max_length=20)),
                ('is_feminine', models.IntegerField()),
                ('locationID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='preloved_auth.location')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
