# Generated by Django 4.2.7 on 2023-11-11 17:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('storage', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=8)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=8)),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('address', models.CharField(max_length=256)),
                ('locationID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='preloved_auth.location')),
            ],
        ),
        migrations.CreateModel(
            name='ShopUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_no', models.CharField(max_length=20)),
                ('is_feminine', models.IntegerField()),
                ('locationID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='preloved_auth.location')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ShopOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phoneNumber', models.CharField(max_length=20)),
                ('imageID1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='image1_shopowners', to='storage.file')),
                ('imageID2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='image2_shopowners', to='storage.file')),
                ('storeID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='preloved_auth.store')),
                ('userID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('imageID1', 'imageID2')},
            },
        ),
    ]
