# Generated by Django 4.2.7 on 2023-11-30 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
        ('preloved_auth', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shopowner',
            old_name='imageID1',
            new_name='image1Slug',
        ),
        migrations.RenameField(
            model_name='shopowner',
            old_name='imageID2',
            new_name='image2Slug',
        ),
        migrations.AlterUniqueTogether(
            name='shopowner',
            unique_together={('image1Slug', 'image2Slug')},
        ),
        migrations.AddField(
            model_name='store',
            name='ownerID',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='preloved_auth.shopowner'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='shopowner',
            name='storeID',
        ),
    ]
