# Generated by Django 4.2.7 on 2023-11-30 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('preloved_auth', '0002_rename_imageid1_shopowner_image1slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='address_plain',
            field=models.CharField(default=0, max_length=1086),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shopowner',
            name='locationID',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='preloved_auth.location'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='location',
            name='latitude',
            field=models.DecimalField(decimal_places=7, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='longitude',
            field=models.DecimalField(decimal_places=7, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
