# Generated by Django 4.2.7 on 2023-11-30 18:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('preloved_auth', '0003_location_address_plain_shopowner_locationid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopowner',
            name='userID',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shopuser',
            name='locationID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='preloved_auth.location'),
        ),
    ]
