# Generated by Django 4.2.7 on 2023-12-01 04:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('preloved_auth', '0004_alter_shopowner_userid_alter_shopuser_locationid'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='shopowner',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='shopowner',
            name='isVerified',
            field=models.IntegerField(default=0),
        ),
        migrations.RemoveField(
            model_name='shopowner',
            name='image1Slug',
        ),
        migrations.RemoveField(
            model_name='shopowner',
            name='image2Slug',
        ),
        migrations.CreateModel(
            name='ShopVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idSlug1', models.CharField(max_length=256)),
                ('idSlug2', models.CharField(max_length=256)),
                ('selfieSlug', models.CharField(max_length=256)),
                ('shopOwnerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='preloved_auth.shopowner')),
            ],
            options={
                'unique_together': {('idSlug1', 'idSlug2', 'selfieSlug')},
            },
        ),
    ]
