# Generated by Django 4.2.7 on 2023-12-04 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('preloved_auth', '0007_staff'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='shopverification',
            unique_together=set(),
        ),
    ]
