# Generated by Django 4.2.8 on 2023-12-08 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0001_initial'),
        ('preloved_auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('statusID', models.AutoField(primary_key=True, serialize=False)),
                ('status_name', models.CharField(max_length=255)),
                ('level', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('ticketID', models.AutoField(primary_key=True, serialize=False)),
                ('itemID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='store.item')),
                ('status', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='tickets.status')),
                ('storeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='store.store')),
                ('userID', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='preloved_auth.shopuser')),
            ],
        ),
    ]
