# Generated by Django 4.2.7 on 2023-11-24 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0002_item_tag_slug_itemtag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('statusID', models.AutoField(primary_key=True, serialize=False)),
                ('status_name', models.CharField(max_length=255)),
                ('level', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('ticketID', models.AutoField(primary_key=True, serialize=False)),
                ('itemID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='store.item')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='tickets.status')),
                ('storeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='store.store')),
            ],
        ),
    ]
