# Generated by Django 4.2.9 on 2024-01-13 09:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='ticket',
            name='expected_buyer_fulfillment',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='expected_seller_fulfillment',
            field=models.DateField(null=True),
        ),
    ]
